import { createOpenAPI } from 'fumadocs-openapi/server';

// Auto-generated by `tools/generate-onebot-openapi.mjs` in the main
// SnowLuma repo. Re-run that script whenever an `h.registerAction`
// call is added / changed and re-build the docs to refresh.
export const openapi = createOpenAPI({
  input: ['./content/api/openapi.json'],
});
